
CREATE TABLE [dbo].[SqlDatatype](
	[Id] [int] NOT NULL,
	[Name] [varchar](1000) NOT NULL,
 CONSTRAINT [PK_SqlDatatype] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO


